name: X
on:
  pull_request_review:
    types: [submitted]

jobs:
  x1:
    if: ${{ github.event_name == 'pull_request_review' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v4
      - name: Shell
        run: |
          echo ok
